resources:
- name: concourse
  type: git
  source:
    uri: https://github.com/narmadapittala/concourse.git
    branch: main
    

jobs:
- name: build-and-deploy
  plan:
  - get: concourse
    trigger: true
  - task: build-image
    config:
      platform: linux
      image_resource:
        type: docker-image
        source: {repository: ubuntu}
      inputs:
      - name: concourse
      run:
        path: /bin/bash
        args:
        - -c
        - |
          cd concourse
          docker build -t my-docker-image .
  - task: deploy-image
    config:
      platform: linux
      image_resource:
        type: docker-image
        source: {repository: ubuntu}
      inputs:
      - name: concourse
      run:
        path: /bin/bash
        args:
        - -c
        - |
          docker run -d --name my-container my-docker-image
