resources:
- name: concourse
  type: git
  source: https://github.com/narmadapittala/concourse.git
    uri: 
    branch: master

jobs:
- name: unit
  plan:
  - get: concourse
    trigger: true
  - task: unit
    file: concourse/ci/test.yml
